name: Deploy to Amazon ECS

on:
  push:
    branches: ["master"]

env:
  AWS_REGION: us-east-1 # 设置AWS区域
  ECR_REPOSITORY: my-app-repo # ECR仓库名称
  ECS_SERVICE: my-app-service # ECS服务名称
  ECS_CLUSTER: my-app-cluster # ECS集群名称
  CONTAINER_NAME: my-app-container # 容器名称

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: test
        run: npm run test

      - name: build
        run: npm run build

      - name: deploy
        run: npm run deploy
